### ISSUE TITLE
migrate CI

### ISSUE THREAD

**Issue by iyuuya** [iyuuya/jkf#3]
travis → github action

**Comment by gemmaro** [comment]
Not familiar with CodeClimate, but apparently [there is a subscription fee](https://github.com/marketplace/code-climate/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4zMzY=) for the application for GitHub Actions. If you have already signed up for a plan, that's fine, but if not, I feel like I'd like to cut back. What do you think?

**Comment by iyuuya** [comment]
その昔無料だったから入れてただけなので外して問題ないと考えています
もし無料で使えるものがあればそれに置き換えるのも良いと思いますー
